In [42]:
import json
import pandas as pd
pd.set_option('display.max_columns', None)

with open('full_format_recipes.json', 'r') as f:
    data = json.load(f)
data_withsteps = pd.DataFrame(data)

# EDA
<p style="font-size:20px; color:#4CAF50; font-weight:bold;">Exploratory Data Analysis</p>


In [43]:
data_withsteps.head()

directions   fat  \
0  [Combine first 9 ingredients in heavy medium s...  23.0   
1  [Mix basil, mayonnaise and butter in processor...  79.0   
2  [Stir together soy sauce, sugar, sesame oil, w...  10.0   
3  [Preheat oven to 350°F. Coat cake pans with no...  48.0   
4  [Using the tip of a paring knife, score an X i...   3.0   

                       date  \
0  2004-08-20T04:00:00.000Z   
1  2004-08-20T04:00:00.000Z   
2  2004-08-20T04:00:00.000Z   
3  2012-09-18T04:00:00.000Z   
4  2014-06-17T04:00:00.000Z   

                                          categories  calories  \
0  [Food Processor, Onion, Pork, Bake, Bastille D...     403.0   
1  [Sandwich, Food Processor, Tomato, Kid-Friendl...     948.0   
2  [Beef, Ginger, Sauté, Stir-Fry, Quick & Easy, ...     170.0   
3  [Cake, Chocolate, Fruit, Dessert, Bake, Kid-Fr...     766.0   
4        [Sauce, Mustard, Peach, Chive, Bon Appétit]     134.0   

                                                desc  protein  rating  \
0  This uses the same ingredients found in boudin...     18.0   4.375   
1  This recipe can be prepared in 45 minutes or l...     19.0   4.375   
2                                            Bulgogi      7.0   4.375   
3  This cake is perfect for beginners—it's moist,...     12.0   4.375   
4  Where a chutney and mustard sauce overlap. Cho...      4.0   3.125   

                                               title  \
0        Boudin Blanc Terrine with Red Onion Confit    
1                                     The Best Blts    
2                             Korean Marinated Beef    
3  Banana-Chocolate Chip Cake With Peanut Butter ...   
4                                     Peach Mustard    

                                         ingredients  sodium  total_steps  \
0  [1 1/2 cups whipping cream, 2 medium onions, c...  1439.0            5   
1  [2 1/2 cups (lightly packed) fresh basil leave...  1042.0            3   
2  [1/4 cup soy sauce, 1 tablespoon sugar, 2 teas...  1272.0            3   
3  [Nonstick vegetable oil spray, 3 cups all-purp...   439.0            5   
4  [1 large ripe peach, 2 tablespoons sugar, 1 te...  1394.0            3   

   total_ingredients  
0                 28  
1                  9  
2                 10  
3                 18  
4                  8

In [44]:
# data_withsteps.to_csv('full_format_recipes.csv')

In [45]:

data_withsteps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7021 entries, 0 to 7020
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   directions         7021 non-null   object 
 1   fat                7021 non-null   float64
 2   date               7021 non-null   object 
 3   categories         7021 non-null   object 
 4   calories           7021 non-null   float64
 5   desc               7021 non-null   object 
 6   protein            7021 non-null   float64
 7   rating             7021 non-null   float64
 8   title              7021 non-null   object 
 9   ingredients        7021 non-null   object 
 10  sodium             7021 non-null   float64
 11  total_steps        7021 non-null   int64  
 12  total_ingredients  7021 non-null   int64  
dtypes: float64(5), int64(2), object(6)
memory usage: 713.2+ KB


In [46]:
data_withsteps.describe()

fat     calories      protein       rating       sodium  \
count  7021.000000  7021.000000  7021.000000  7021.000000  7021.000000   
mean     24.459906   430.717419    17.999715     3.852639   415.552201   
std      20.756511   283.885946    21.135332     1.200490   374.879042   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%      10.000000   223.000000     4.000000     3.750000   111.000000   
50%      19.000000   364.000000     9.000000     4.375000   303.000000   
75%      33.000000   581.000000    26.000000     4.375000   636.000000   
max     135.000000  1497.000000   203.000000     5.000000  1499.000000   

       total_steps  total_ingredients  
count  7021.000000        7021.000000  
mean      4.174761          10.905996  
std       2.186613           4.499129  
min       2.000000           1.000000  
25%       3.000000           8.000000  
50%       4.000000          10.000000  
75%       5.000000          13.000000  
max      24.000000          34.000000

In [47]:
data_withsteps.sort_values(by='calories', ascending=False).head(10)['calories']

1426    1497.0
5205    1497.0
2514    1496.0
2373    1492.0
5141    1488.0
319     1488.0
3133    1484.0
591     1478.0
3409    1472.0
6783    1470.0
Name: calories, dtype: float64

In [48]:
resep = pd.read_csv('full_format_recipes.csv')

In [49]:
resep.isnull().sum()

Unnamed: 0           0
directions           0
fat                  0
date                 0
categories           0
calories             0
desc                 0
protein              0
rating               0
title                0
ingredients          0
sodium               0
total_steps          0
total_ingredients    0
dtype: int64

In [50]:
data_withsteps[data_withsteps['calories'] > 1500].count()

directions           0
fat                  0
date                 0
categories           0
calories             0
desc                 0
protein              0
rating               0
title                0
ingredients          0
sodium               0
total_steps          0
total_ingredients    0
dtype: int64

In [51]:
data_withsteps.sort_values(by='sodium', ascending=False).head(10)

directions   fat  \
3641  [Melt 2 tablespoons butter in small saucepan o...  51.0   
3012  [1. Combine the coconut milk, fish sauce, lemo...   6.0   
5406  [Heat olive oil in heavy large saucepan over m...  15.0   
1166  [Mix first 4 ingredients in small bowl. Set di...   3.0   
6475  [Cover potatoes with salted cold water by 1 in...  89.0   
6796  [Put oven rack in middle position and preheat ...  72.0   
2909  [Bring large pot of salted water to boil. Add ...  75.0   
349   [Heat oven to 375°F with rack in middle., Mean...  62.0   
2461  [In a small sauté pan, heat 1 tablespoon oil o...  47.0   
3610  [Put pork, water, salt, and garlic in a 5- to ...  30.0   

                          date  \
3641  2004-08-20T04:00:00.000Z   
3012  2014-01-28T04:00:00.000Z   
5406  2004-08-20T04:00:00.000Z   
1166  2004-08-20T04:00:00.000Z   
6475  2007-02-15T19:38:10.000Z   
6796  2005-07-19T19:22:16.000Z   
2909  2004-08-20T04:00:00.000Z   
349   2011-10-27T04:00:00.000Z   
2461  2014-04-16T04:00:00.000Z   
3610  2006-06-01T04:00:00.000Z   

                                             categories  calories  \
3641  [Sandwich, Broil, Lunch, Ham, Swiss Cheese, Bo...     794.0   
3012  [Rice, Shellfish, Dinner, Lunar New Year, Seaf...     278.0   
5406  [Soup/Stew, Leafy Green, Potato, Vegetarian, S...     601.0   
1166  [Leafy Green, Shellfish, Vegetable, Appetizer,...      80.0   
6475  [Citrus, Herb, Onion, Potato, Braise, Christma...    1299.0   
6796  [Chicken, Rice, Sauté, Quick & Easy, Shrimp, W...    1240.0   
2909  [Milk/Cream, Dairy, Herb, Pasta, Shellfish, Ve...    1038.0   
349   [Beef, Pork, Roast, Kid-Friendly, Back to Scho...     880.0   
2461                   [Easter, Mozzarella, Prosciutto]     899.0   
3610  [Blender, Garlic, Herb, Pork, Tomato, Hot Pepp...     468.0   

                                                   desc  protein  rating  \
3641  Offer a plum-tomato salad with the sandwiches....     41.0   5.000   
3012  Shrimp absorbs the flavors of a marinade rapid...     27.0   4.375   
5406  Reflecting the cuisines of Israel and the surr...     29.0   4.375   
1166  Wrapped foods, such as the Vietnamese spring r...      3.0   3.750   
6475  While this impressive roast cooks, it slowly t...     90.0   4.375   
6796  Pair this surf-and-turf dish with white rice t...    131.0   3.750   
2909  Asparagus, green beans and peas give this past...     35.0   4.375   
349   It's good news for America that grass-fed beef...     55.0   3.125   
2461  Homey and comforting, this lovely pie comes to...     42.0   3.750   
3610                 Carne de Puerco con Chile Guajillo     30.0   3.750   

                                                  title  \
3641                                   Croque-Monsieur    
3012                              Curry-Coconut Shrimp    
5406             Lentil Stew with Spinach and Potatoes    
1166         Vietnamese-Style Spring Rolls with Shrimp    
6475  Braised Veal Breast with Potato-and-Onion Stuf...   
6796            Chicken Breasts with Rock-Shrimp Sauce    
2909   Three-Green Pasta with Scallops and Pesto Sauce    
349         Grass-Fed Beef Meatloaf in a Bacon Blanket    
2461  Pretty Easter Pasta Pie (Crostata di tagliolin...   
3610                          Pork with Guajillo Sauce    

                                            ingredients  sodium  total_steps  \
3641  [2 tablespoons butter, 2 tablespoons all purpo...  1499.0            2   
3012  [1/4 cup unsweetened coconut milk, 1 1/2 table...  1498.0            3   
5406  [2 tablespoons olive oil, 2 large garlic clove...  1495.0            3   
1166  [1/4 cup fish sauce (nam pla), 2 tablespoons t...  1493.0            4   
6475  [3/4 pound medium Yukon Gold potatoes (2 to 3)...  1491.0            9   
6796  [4 small skinless boneless chicken breast halv...  1491.0            7   
2909  [1 pound asparagus, trimmed, cut into 1 1/2-in...  1490.0            3   
349   [1 cup fresh bread crumbs (ground in food proc...  1487.0    

In [52]:
data_withsteps[data_withsteps['sodium'] > 1500].count()

directions           0
fat                  0
date                 0
categories           0
calories             0
desc                 0
protein              0
rating               0
title                0
ingredients          0
sodium               0
total_steps          0
total_ingredients    0
dtype: int64

In [53]:
data_withsteps[data_withsteps['calories'] < 50].count()

directions           173
fat                  173
date                 173
categories           173
calories             173
desc                 173
protein              173
rating               173
title                173
ingredients          173
sodium               173
total_steps          173
total_ingredients    173
dtype: int64

In [54]:
data_withsteps[data_withsteps['calories'] < 50].head(10)

directions  fat  \
127  [Put oven rack in middle position and preheat ...  0.0   
128  [Preheat oven to 400°F., In a dry small heavy ...  1.0   
131  [Preheat oven to 450°F., Arrange veal bones in...  1.0   
146  [Mix first 4 ingredients in small bowl to blen...  4.0   
150  [Cook haricots verts in a large pot of boiling...  1.0   
175  [Stir together yeast, 1 teaspoon brown sugar, ...  1.0   
197  [Blend 4 tablespoons soy sauce, 1/4 cup ginger...  1.0   
221  [Heat heavy large skillet over medium-high hea...  1.0   
225  [Trim root ends of radishes so radishes will s...  3.0   
227  [Prepare grill., Trim roots and ends from spri...  1.0   

                         date  \
127  2004-08-20T04:00:00.000Z   
128  2004-08-20T04:00:00.000Z   
131  2004-08-20T04:00:00.000Z   
146  2004-08-20T04:00:00.000Z   
150  2007-11-16T04:56:24.000Z   
175  2009-09-22T04:00:00.000Z   
197  2004-08-20T04:00:00.000Z   
221  2004-08-20T04:00:00.000Z   
225  2004-08-20T04:00:00.000Z   
227  2004-08-20T12:48:48.000Z   

                                            categories  calories  \
127  [Bread, Condiment/Spread, Food Processor, Bake...      14.0   
128    [Bake, Cocktail Party, Low Cal, Spice, Gourmet]      21.0   
131  [Soup/Stew, Vegetable, Veal, Fall, Simmer, Gou...      29.0   
146  [Chicken, Tomato, Cocktail Party, Mayonnaise, ...      47.0   
150  [Egg, Onion, Christmas, Cocktail Party, Quick ...      19.0   
175  [Mustard, Bake, St. Patrick's Day, Oscars, Che...      46.0   
197  [Beef, Ginger, Appetizer, Fry, Super Bowl, Kid...      45.0   
221  [Sauce, Blender, Garlic, Pepper, Low Carb, Qui...      43.0   
225  [Cocktail Party, Vegetarian, Quick & Easy, Cre...      43.0   
227  [Citrus, Onion, Side, Quick & Easy, Low/No Sug...      14.0   

                                                  desc  protein  rating  \
127  As a crisp topping for pasta or steamed vegeta...      1.0   5.000   
128  This recipe can be prepared in 45 minutes or l...      0.0   3.750   
131  Active time: 1 1/2 hr Start to finish: 18 hr (...      4.0   5.000   
146  If you cannot find smoked chicken, use smoked ...      2.0   4.375   
150  It looks like a Japanese roll—but it's not! Gr...      2.0   3.750   
175  Simultaneously salty, sharp, spicy, and sweet ...      1.0   4.375   
197  Amy likes to make these for parties. Wonton wr...      2.0   4.375   
221  This recipe is an accompaniment for <epi:recip...      2.0   4.375   
225             Can be prepared in 45 minutes or less.      1.0   0.000   
227                              Grilled Spring Onions      0.0   3.750   

                                                 title  \
127                           Toasted Baguette Crumbs    
128                                Spiced Pita Toasts    
131                                        Veal Stock    
146  Smoked Chicken Salad on Toasted Corn Bread Tri...   
150                Green-Bean and Prosciutto Negimaki    
175  Country Ham and Cheddar Pretzel Bites with Jal...   
197  Beef and Broccoli Wontons with Ginger Dipping ...   
221                        Ancho-Guajillo Chile Sauce    
225                  Radishes with Chive Cream Cheese    
227                                 Cebollitas Asadas    

                                           ingredients  sodium  total_steps  \
127  [1 (12-inch) piece day-old baguette, cut into ...    30.0            2   
128  [4 teaspoons cumin seeds, 1 teaspoon coarse sa...    38.0            3   
131  [5 lb veal knuckle bones, 4 qt plus 1 cup wate...    57.0            6   
146  [6 tablespoons mayonnaise, 1 tablespoon fresh ...    25.0            3   
150  [1/2 pound haricots verts, trimmed, 3 hard-boi...   130.0            5   
175  [1 1/2 teaspoons active dry yeast, 2 tablespoo...   342.0            8   
197  [6 tablespoons soy sauce, 1/4 cup plus 2 teasp...   166.0            3   
221  [9 dried ancho chiles (scant 4 ounces), stemme...   478.0            2   
225  [8 medium radishes, 2 tablespoons cream cheese...    55.

In [55]:
duplicate_rows = data_withsteps.duplicated(subset=['title', 'calories', 'protein', 'fat', 'sodium'])
duplicate_count = duplicate_rows.sum()
duplicate_count


0

# insights from EDA

- Dari hasil analisis data, terdapat banyak nilai kosong yang perlu dibersihkan.
- Terdapat nilai kalori yang sangat tinggi hingga lebih dari 30.000, yang tidak realistis untuk satu porsi makanan. Untuk memastikan data lebih representatif, kita perlu menetapkan batasan (threshold) yang realistis. Kalori yang wajar untuk makanan bisa dibatasi, misalnya, antara 1.000 hingga 1.500 kalori untuk makanan berkalori tinggi.

- Kandungan sodium juga menunjukkan banyak outlier, dengan beberapa nilai melebihi batas konsumsi harian yang direkomendasikan. Mengingat rata-rata sodium untuk makanan berada di kisaran 800-1.000 mg, kita bisa menetapkan ambang batas sekitar 1.500 mg untuk menjaga data tetap relevan.

- Terdapat sejumlah data duplikat dalam dataset, yang perlu dihapus untuk mencegah redundansi dan kesalahan dalam analisis. Mengidentifikasi duplikat berdasarkan atribut penting seperti judul, kalori, dan bahan akan membantu kita mempertahankan data yang unik.

- Awalnya, data dengan nilai kalori di bawah 50 tampak seperti outlier. Namun, setelah ditinjau lebih lanjut, ternyata data ini merujuk pada resep makanan pendamping seperti saus atau kaldu.

# Data Cleaning

In [56]:
data_withsteps.dropna(inplace=True)

In [57]:
data_withsteps.isnull().sum()

directions           0
fat                  0
date                 0
categories           0
calories             0
desc                 0
protein              0
rating               0
title                0
ingredients          0
sodium               0
total_steps          0
total_ingredients    0
dtype: int64

In [58]:
data_withsteps.describe()

fat     calories      protein       rating       sodium  \
count  7021.000000  7021.000000  7021.000000  7021.000000  7021.000000   
mean     24.459906   430.717419    17.999715     3.852639   415.552201   
std      20.756511   283.885946    21.135332     1.200490   374.879042   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%      10.000000   223.000000     4.000000     3.750000   111.000000   
50%      19.000000   364.000000     9.000000     4.375000   303.000000   
75%      33.000000   581.000000    26.000000     4.375000   636.000000   
max     135.000000  1497.000000   203.000000     5.000000  1499.000000   

       total_steps  total_ingredients  
count  7021.000000        7021.000000  
mean      4.174761          10.905996  
std       2.186613           4.499129  
min       2.000000           1.000000  
25%       3.000000           8.000000  
50%       4.000000          10.000000  
75%       5.000000          13.000000  
max      24.000000          34.000000

In [59]:
data_withsteps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7021 entries, 0 to 7020
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   directions         7021 non-null   object 
 1   fat                7021 non-null   float64
 2   date               7021 non-null   object 
 3   categories         7021 non-null   object 
 4   calories           7021 non-null   float64
 5   desc               7021 non-null   object 
 6   protein            7021 non-null   float64
 7   rating             7021 non-null   float64
 8   title              7021 non-null   object 
 9   ingredients        7021 non-null   object 
 10  sodium             7021 non-null   float64
 11  total_steps        7021 non-null   int64  
 12  total_ingredients  7021 non-null   int64  
dtypes: float64(5), int64(2), object(6)
memory usage: 713.2+ KB


In [60]:
data_withsteps.drop_duplicates(subset=['title', 'calories', 'protein', 'fat', 'sodium'], inplace=True)


In [61]:
data_withsteps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7021 entries, 0 to 7020
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   directions         7021 non-null   object 
 1   fat                7021 non-null   float64
 2   date               7021 non-null   object 
 3   categories         7021 non-null   object 
 4   calories           7021 non-null   float64
 5   desc               7021 non-null   object 
 6   protein            7021 non-null   float64
 7   rating             7021 non-null   float64
 8   title              7021 non-null   object 
 9   ingredients        7021 non-null   object 
 10  sodium             7021 non-null   float64
 11  total_steps        7021 non-null   int64  
 12  total_ingredients  7021 non-null   int64  
dtypes: float64(5), int64(2), object(6)
memory usage: 713.2+ KB


In [62]:
data_withsteps.describe()

fat     calories      protein       rating       sodium  \
count  7021.000000  7021.000000  7021.000000  7021.000000  7021.000000   
mean     24.459906   430.717419    17.999715     3.852639   415.552201   
std      20.756511   283.885946    21.135332     1.200490   374.879042   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%      10.000000   223.000000     4.000000     3.750000   111.000000   
50%      19.000000   364.000000     9.000000     4.375000   303.000000   
75%      33.000000   581.000000    26.000000     4.375000   636.000000   
max     135.000000  1497.000000   203.000000     5.000000  1499.000000   

       total_steps  total_ingredients  
count  7021.000000        7021.000000  
mean      4.174761          10.905996  
std       2.186613           4.499129  
min       2.000000           1.000000  
25%       3.000000           8.000000  
50%       4.000000          10.000000  
75%       5.000000          13.000000  
max      24.000000          34.000000

In [63]:
data_withsteps = data_withsteps[data_withsteps['calories'] < 1500]

In [64]:
data_withsteps.describe()

fat     calories      protein       rating       sodium  \
count  7021.000000  7021.000000  7021.000000  7021.000000  7021.000000   
mean     24.459906   430.717419    17.999715     3.852639   415.552201   
std      20.756511   283.885946    21.135332     1.200490   374.879042   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%      10.000000   223.000000     4.000000     3.750000   111.000000   
50%      19.000000   364.000000     9.000000     4.375000   303.000000   
75%      33.000000   581.000000    26.000000     4.375000   636.000000   
max     135.000000  1497.000000   203.000000     5.000000  1499.000000   

       total_steps  total_ingredients  
count  7021.000000        7021.000000  
mean      4.174761          10.905996  
std       2.186613           4.499129  
min       2.000000           1.000000  
25%       3.000000           8.000000  
50%       4.000000          10.000000  
75%       5.000000          13.000000  
max      24.000000          34.000000

In [65]:
data_withsteps = data_withsteps[data_withsteps['sodium'] < 1500]

In [66]:
data_withsteps.describe()

fat     calories      protein       rating       sodium  \
count  7021.000000  7021.000000  7021.000000  7021.000000  7021.000000   
mean     24.459906   430.717419    17.999715     3.852639   415.552201   
std      20.756511   283.885946    21.135332     1.200490   374.879042   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%      10.000000   223.000000     4.000000     3.750000   111.000000   
50%      19.000000   364.000000     9.000000     4.375000   303.000000   
75%      33.000000   581.000000    26.000000     4.375000   636.000000   
max     135.000000  1497.000000   203.000000     5.000000  1499.000000   

       total_steps  total_ingredients  
count  7021.000000        7021.000000  
mean      4.174761          10.905996  
std       2.186613           4.499129  
min       2.000000           1.000000  
25%       3.000000           8.000000  
50%       4.000000          10.000000  
75%       5.000000          13.000000  
max      24.000000          34.000000

In [67]:
data_withsteps['total_steps'] = data_withsteps['directions'].apply(
    lambda x: len(x) if isinstance(x, list) else len(eval(x)) if isinstance(x, str) and x.startswith('[') else 0
)

data_withsteps['total_ingredients'] = data_withsteps['ingredients'].apply(
    lambda x: len(x) if isinstance(x, list) else len(eval(x)) if isinstance(x, str) and x.startswith('[') else 0
)
data_withsteps.head()

directions   fat  \
0  [Combine first 9 ingredients in heavy medium s...  23.0   
1  [Mix basil, mayonnaise and butter in processor...  79.0   
2  [Stir together soy sauce, sugar, sesame oil, w...  10.0   
3  [Preheat oven to 350°F. Coat cake pans with no...  48.0   
4  [Using the tip of a paring knife, score an X i...   3.0   

                       date  \
0  2004-08-20T04:00:00.000Z   
1  2004-08-20T04:00:00.000Z   
2  2004-08-20T04:00:00.000Z   
3  2012-09-18T04:00:00.000Z   
4  2014-06-17T04:00:00.000Z   

                                          categories  calories  \
0  [Food Processor, Onion, Pork, Bake, Bastille D...     403.0   
1  [Sandwich, Food Processor, Tomato, Kid-Friendl...     948.0   
2  [Beef, Ginger, Sauté, Stir-Fry, Quick & Easy, ...     170.0   
3  [Cake, Chocolate, Fruit, Dessert, Bake, Kid-Fr...     766.0   
4        [Sauce, Mustard, Peach, Chive, Bon Appétit]     134.0   

                                                desc  protein  rating  \
0  This uses the same ingredients found in boudin...     18.0   4.375   
1  This recipe can be prepared in 45 minutes or l...     19.0   4.375   
2                                            Bulgogi      7.0   4.375   
3  This cake is perfect for beginners—it's moist,...     12.0   4.375   
4  Where a chutney and mustard sauce overlap. Cho...      4.0   3.125   

                                               title  \
0        Boudin Blanc Terrine with Red Onion Confit    
1                                     The Best Blts    
2                             Korean Marinated Beef    
3  Banana-Chocolate Chip Cake With Peanut Butter ...   
4                                     Peach Mustard    

                                         ingredients  sodium  total_steps  \
0  [1 1/2 cups whipping cream, 2 medium onions, c...  1439.0            5   
1  [2 1/2 cups (lightly packed) fresh basil leave...  1042.0            3   
2  [1/4 cup soy sauce, 1 tablespoon sugar, 2 teas...  1272.0            3   
3  [Nonstick vegetable oil spray, 3 cups all-purp...   439.0            5   
4  [1 large ripe peach, 2 tablespoons sugar, 1 te...  1394.0            3   

   total_ingredients  
0                 28  
1                  9  
2                 10  
3                 18  
4                  8

In [68]:
print(data_withsteps[['total_steps', 'total_ingredients']].describe())

       total_steps  total_ingredients
count  7021.000000        7021.000000
mean      4.174761          10.905996
std       2.186613           4.499129
min       2.000000           1.000000
25%       3.000000           8.000000
50%       4.000000          10.000000
75%       5.000000          13.000000
max      24.000000          34.000000


In [69]:
data_withsteps[data_withsteps['total_steps'] == 2]

directions   fat  \
5     [Purée vegetable juice, spinach, and escarole ...  31.0   
10    [Gently combine the eggs, cucumbers, shallots,...  20.0   
13    [Cut off and discard 1 inch from stem ends of ...  10.0   
16    [Preheat oven to 425°F. Whisk 2 tablespoons oi...  31.0   
17    [Heat oil in heavy large pot over medium heat....  21.0   
...                                                 ...   ...   
7009  [Melt butter in heavy large pot over medium he...  25.0   
7014  [Combine oil, lemon juice, rosemary and genero...  95.0   
7017  [Drain clams, reserving juices. Sauté salt por...  10.0   
7018  [1. Preheat the oven to 400°F. Spray a baking ...  70.0   
7019  [Bring broth to simmer in saucepan.Remove from...  28.0   

                          date  \
5     2004-08-20T04:00:00.000Z   
10    2011-03-31T04:00:00.000Z   
13    2004-08-20T04:00:00.000Z   
16    2005-10-01T04:00:00.000Z   
17    2004-08-20T04:00:00.000Z   
...                        ...   
7009  2004-08-20T04:00:00.000Z   
7014  2004-08-20T04:00:00.000Z   
7017  2004-08-20T04:00:00.000Z   
7018  2014-03-21T04:00:00.000Z   
7019  2008-02-28T22:06:54.000Z   

                                             categories  calories  \
5     [Soup/Stew, Garlic, Onion, No-Cook, Vegetarian...     382.0   
10    [Egg, Herb, Vegetable, Side, Easter, Vegetaria...     215.0   
13    [Garlic, Side, Sauté, Vegetarian, Quick & Easy...     107.0   
16    [Fish, Leafy Green, Pasta, Tomato, Bake, Quick...     634.0   
17    [Soup/Stew, Chicken, Garlic, Tomato, Sauté, Qu...     338.0   
...                                                 ...       ...   
7009  [Milk/Cream, Mussel, White Wine, Winter, Parsl...     600.0   
7014  [Beef, Marinate, Low Carb, Wheat/Gluten-Free, ...    1168.0   
7017  [Soup/Stew, Milk/Cream, Pork, Potato, Sauté, T...     235.0   
7018  [Chicken, Poultry, Bake, Passover, Fennel, Sha...    1086.0   
7019  [Side, Kid-Friendly, High Fiber, Dinner, Parme...     671.0   

                                                   desc  protein  rating  \
5     This uncooked soup isn't for the timid — raw g...      5.0   4.375   
10    The glories of summer are captured in this pal...      6.0   3.750   
13          Active time: 25 min Start to finish: 30 min      4.0   4.375   
16    Kristi Parnell of San Marcos, California, writ...     44.0   4.375   
17    A homey yet sophisticated soup that's great fo...     14.0   4.375   
...                                                 ...      ...     ...   
7009  Serve these mussels with a frisée salad dresse...     55.0   4.375   
7014  This simple marinade and a fast grilling bring...     74.0   3.750   
7017  The early Yankees often cooked local shellfish...     17.0   3.125   
7018                             Kosher Status: Poultry     78.0   5.000   
7019  Cooking the artichokes with the rice infuses t...     22.0   4.375   

                                                  title  \
5                            Raw Cream of Spinach Soup    
10                            Cucumber-Basil Egg Salad    
13                               Sauteed Broccoli Rabe    
16    Baked Halibut with Orzo, Spinach, and Cherry T...   
17                                   Mexican Lime Soup    
...                                                 ...   
7009                            Mussels in Cream Sauce    
7014                  Lemon and Rosemary T-Bone Steaks    
7017                Shellfish Chowder with Fresh Thyme    
7018  Crispy Salt and Pepper Chicken with Caramelize...   
7019                    Artichoke and Parmesan Risotto    

                                            ingredients  sodium  total_steps  \
5     [2 cups fresh tomato and/or carrot juice (from...   977.0            2   
10    [6 hard-cooked eggs, diced (2 cups), 3/4 cup s...   250.0            2   
13    [2 lb broccoli rabe, 3 large garlic cloves, th...   329.0            2   
16    [4 tablespoons extra-virgin olive oil, divided...   181.0            2   
17  

In [70]:
data_withsteps[data_withsteps['total_ingredients'] < 3]


directions   fat  \
97    [In large stockpot, bring 4 gallons water to r...   3.0   
115   [Rub outsides of peppers with oil, then arrang...   2.0   
127   [Put oven rack in middle position and preheat ...   0.0   
338   [Blend sugar and vanilla bean in processor unt...   0.0   
356   [1. Preheat the oven to 325°F. Place the sugar...   0.0   
379   [Prepare grill., Peel back corn husks carefull...   2.0   
552   [Melt butter in a shallow, heavy pan set on a ...  10.0   
553   [Line a sieve with 3 layers of cheesecloth and...  23.0   
673   [Mix the dough by placing 3 cups of flour in a...   1.0   
945   [Using a small slicer or a mandoline, slice th...  54.0   
1053  [1. Finely chop 1 1/2 to 2 pounds chocolate. S...  17.0   
1153  [Combine kombu and 8 cups water in a large sau...   0.0   
1296  [1. Preparing the cream. Pour the cream into a...  24.0   
1375  [Bring carrots, 2 Tbsp. sugar, and 1/4 cup wat...   0.0   
1455  [Heat the olive oil with the almonds in a smal...  13.0   
1496  [Place two-thirds of the chocolate in a heatpr...  15.0   
1715  [Preheat oven to 400° F., Diagonally cut twent...   1.0   
1763  [In a 2 1/2-to-3 quart heavy saucepan with a t...   1.0   
1764  [In a large bowl (large enough to hold at leas...   1.0   
1897  [In a small saucepan over medium heat, bring t...   0.0   
1954  [Lightly oil a baking sheet., In a dry heavy s...  14.0   
1961  [Remove zest from oranges in long 1/2-inch-wid...   0.0   
2040  [Fill a large pot partially with water. Bring ...   0.0   
2079  [1. In a small saucepan, heat the oil over med...  15.0   
2119  [Brush the bottom of a 9-inch heavy oven-proof...   8.0   
2264  [Stack several collard leaf halves and roll up...   7.0   
2395  [Preheat oven to 400°F., Pierce softest eye of...  22.0   
2475  [Prepare grill for cooking or heat a well-seas...  43.0   
2492  [Use a vegetable peeler to remove the peel fro...   0.0   
2495  [Tempering determines the final gloss, hardnes...   0.0   
2551  [1. Place sugar in an ovenproof shallow pan an...   0.0   
2879  [Cut the vanilla bean in quarters and place in...   0.0   
2946  [Preheat oven to 350°F., Bake chestnuts on a b...   0.0   
3471  [Prepare a hardwood-charcoal fire in a grill. ...   0.0   
3857  [Pat bacon dry and cook in 2 batches in oil (1...  10.0   
4000  [Bring butter to a boil in a small heavy sauce...  31.0   
4115  [Standing mango upright, cut two lengthwise sl...   1.0   
4155  [Cut grapefruits in half and juice them (reser...   0.0   
4625  [Put rice in a 3- to 4-quart heavy saucepan an...   1.0   
4782  [If using a top-down broiler, arrange rack on ...  85.0   
4828  [1. Put the rice in a large bowl (or in the in...   0.0   
4834  [Preheat oven to 350°F., Arrange bread slices ...   6.0   
5040  [Preheat the oven to 150°F/65°C. Pour the butt...   5.0   
5168  [Squeeze juice from 2 lemon halves into large ...   0.0   
5214  [Bring the preserves and rum to a boil in a sm...   0.0   
5317  [Bring 3 to 4 quarts water to a boil in a past...   0.0   
5443  [Place rice in a large saucepan, add water to ...   1.0   
5454  [Rinse rice in a fine-mesh sieve until water i...   0.0   
5564  [1. Let meat stand at cool room temperature ab...  11.0   
5647  [Heat the cream in a heavy sauté pan and gentl...  28.0   
5665  [Arrange the turkey halves bone side down on t...  12.0   
5692  [Rinse and drain barley or corn. Bring water w...   1.0   
5696  [Build a fire in a smoker/grill for indirect h...  42.0   
6062  [Gently mix together the rice and yukari shiso...   0.0   
6183  [1. Cook the quinoa in a large nonstick skille...   3.0   
6271  [Prepare a grill for medium heat. Grill corn, ...   1.0   
6373  [Set a coffee filter in a sieve set over a hea...  33.0   
6392  [Preheat oven to 450°F., Toss parsnips with oi...   8.0   
6601  [Place fresh masa or masa harina mixture in la...   1.0   

                          date  \
97    2006-05-16T20:13:00.000Z   
115   2009-03-12T04:00:00.000Z   
127   2004-08-20T04:00:00.000Z   
338   20

In [71]:
import ast

# Convert strings back to lists (if needed)
data_withsteps['ingredients'] = data_withsteps['ingredients'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') else x
)
data_withsteps['directions'] = data_withsteps['directions'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[') else x
)


In [72]:
data_withsteps.to_json('full_format_recipes.json', orient='records', indent=4)

In [75]:
import json

# Validate JSON
with open('full_format_recipes.json', 'r') as f:
    json.load(f)


In [74]:
data_withsteps.to_csv('full_format_recipes.csv')